pms_category:
    resource: "@PMSProjectBundle/Controller/"
    type:     annotation
    prefix:   /projects/categories

pms_project:
    resource: "@PMSProjectBundle/Controller/"
    type:     annotation
    prefix:   /projects/statuses

pms_project:
    resource: "@PMSProjectBundle/Controller/"
    type:     annotation
    prefix:   /projects

pms_user:
    resource: "@PMSUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security_login:
    pattern: /signin
    defaults: { _controller: FOSUserBundle:Security:login }
fos_user_security_check:
    pattern: /signin-check
    defaults: { _controller: FOSUserBundle:Security:check }
fos_user_security_logout:
    pattern: /signout
    defaults: { _controller: FOSUserBundle:Security_logout }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /signup

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_imagine:
    resource: .
    type:     imagine
