services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    pms.twig.inflection_extension:
        class: PMS\UserBundle\Twig\Extension\InflectionExtension
        tags:
            - { name: twig.extension }

    twig.extension.debug:
        class: Twig_Extension_Debug
        tags:
            - { name: twig.extension }

################################################################################
## KnP Menu ####################################################################
################################################################################
    pms_menu.menu_builder:
        class: PMS\UserBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    pms_menu.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: pms_menu.menu_builder
        factory_method: createMainMenu
        arguments: [ "@request", "@service_container" ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    pms_menu.menu.datatable_controls:
        class: Knp\Menu\MenuItem
        factory_service: pms_menu.menu_builder
        factory_method: createDatatableControlMenu
        arguments: [ "@request", "@service_container" ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: datatable_controls }
